apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.mysql.name }}-{{ .Values.mysql.preInstall.name }}
  namespace: {{ .Values.mysql.namespace }}
  labels:
    app: {{ .Values.mysql.label }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.mysql.name }}-{{ .Values.mysql.preInstall.name }}
      labels:
        app: {{ .Values.mysql.label }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}-{{ .Values.mysql.preInstall.name }}
          imagePullPolicy: {{ .Values.mysql.preInstall.image.pullPolicy }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.mysql.name }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          image: {{ .Values.mysql.preInstall.image.name }}:{{ .Values.mysql.preInstall.image.tag }}
      restartPolicy: Never