apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.hookjob.name }}-preUpgrade
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.hookjob.label }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.hookjob.name }}-preUpgrade
      labels:
        app: {{ .Values.hookjob.label }}
    spec:
      containers:
        - name: {{ .Values.hookjob.name }}-preUpgrade
          imagePullPolicy: {{ .Values.hookjob.image.pullPolicy }}
          image: {{ .Values.hookjob.image.name }}:{{ .Values.hookjob.image.tag }}
      restartPolicy: Never